#!/usr/bin/python3

import argparse
from cckrypto import Caesar

def parse_args():
    parser = argparse.ArgumentParser(description="classic crypto crusher")
    parser.add_argument('file', type=str,
                        help="The file with the data to decrypt")

    return parser.parse_args()

def main(args):
    try:
        ciphertext = open(args.file, 'r').read()
    except Exception:
        print("Cannot open " + args.datafile)

    #print(Caesar.crack(ciphertext))

if __name__ == "__main__":
    main(parse_args())
