#!/usr/bin/python

from lantern.modules import vigenere
from lantern.analysis import frequency
from lantern.fitness import ChiSquared

ciphertext = """
CFB BGD CFBR CCW NL'RG KPC HLKUI... NL'VG LIVU SRYSE-MEF LESF FQYH RA
SERSFS WJOR NL HWXKVYEF PSI ZTGKO... KOE DSXJ VF OOEK AHCD CFB DKN PVA SNST
KORQEKY DETO TIL-CJOAVK APN XRZTGVIJZ.  WG'FI SLEP NSDPNCDIU IY UKHZZTU, YV
ZNNQBIU IY VRI RWAVRIKPC.  VRI WLW VREK OAF CSDLTJSRX AO VOETO FQERU BS YSPC-
PNI ZYGPLU, LYK AHQCI WLW CBI CPKG NVFWS QP ARAET SR KOE FOWVYT.

VRMJ PS QEV NVRNN RFD... TJO AFYLF YJ KOE GVITARQX EEK TJO WNPTER, XYL
BGKYKF OH DLV IAWN.  AV TAMO YJL OH K WVYVKMI RSRGKHP LXKCXZUG YSXYVUV ZEPPNI
PSI DHCD GFBLF LI UPRV-MLVHP KP MK DAUX'X IBN DI TIVFKDIVYIPQ KCBTVYRJ, HNF
ISL JANV YJ JRKWMEHLU.  GI VEPNYVV... HNF ISL JANV YJ JRKWMEHLU.  GI JLEM
KJKLR MXSNSEFQI... RUD AYY THLN EW TYIOSRRSS.  YO IOPSV GMKOOWD WBPN EYPFY,
WKDLFBT PKXZVNCVMKF, WKDLFBT TOPZNIQEW SPAU... KRU FOW MECS UU MVZTIPKPJ.
FOW LYZSD CDSDPC DYQSZ, YQE ARNE YKVJ, FOW WYIKET, MLVHT, CXH CPE VY YJ
HNF DVP AO OKOV BS DOPZLVG SX'J MOT YYI VWP QSFK, YGD AV'YE VRI TYIOSRRSS.

AOW, Z HM C MVZTIPKP.  DF CTSQV PS VREK VF EEVZVSKDC.  DF CTSQV PS
VREK VF LEHXPNI ZIFWLG LC NOAV DLVF SCI EEK TJSRB, UOV GLRA TJOC CVOM VMBL.
MA MVZTE KC XYHT QP SLASOKVKPNI ISL, ZOOOXYPNI DLRA YQE AZSL POZVY FQBKZCE OO
JFY.

I CW E YHCMOV, RUD VRMJ PS OI QRUIHOWKV.  YQE QRF SVYT KOIU SRUPVKNYRS,
BWD CFB CCX'X JAOR EW RSL... CPXVY ANV, AV'YE CVP RSIMO."""

decryptions = vigenere.crack(ciphertext, ChiSquared(frequency.english.unigrams))
print(decryptions[0])
